# ./.github/workflows/vitest_pull_request_tests.yml

# This workflow will do a clean installation of node dependencies
# then cache/restore them
# then build the source code (currently disabled)
# then run tests across different versions of node (only node 16.x for Vitest currently)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Vitest Run Tests

on:
  pull_request:
    branches: [ "main" ]
  # push:
    # branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      # - run: npm run generate --if-present
      - run: npm test